version: "2"

run:
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - err113
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - goprintffuncname
    - importas
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - reassign
    - revive
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign

  disable:
    - copyloopvar
    - exptostd
    - intrange
    - gosec
    - asciicheck
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dupl
    - dupword
    - errchkjson
    - errname
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - gosmopolitan
    - grouper
    - iface
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - recvcheck
    - rowserrcheck
    - spancheck
    - staticcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - unused
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      enabled-checks:
        - deferInLoop
      disabled-checks:
        - commentFormatting
        - ifElseChain
        - elseif
        - wrapperFunc
    nakedret:
      max-func-lines: 30
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
        text: do not define dynamic errors
      - linters:
          - revive
        text: if-return
      - linters:
          - revive
        text: var-naming
      - linters:
          - revive
        text: error-return
      - linters:
          - revive
        text: package-comments
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: indent-error-flow
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: exported
      - linters:
          - revive
        text: receiver-naming
      - linters:
          - revive
        text: unexported-return
      - linters:
          - noctx
        text: "net.(Listen|ListenPacket) must not be called"
      - linters:
          - noctx
        text: "os/exec.Command must not be called"
    paths:
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$
      - .*\.alt$
      - .*\.tmp$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$
